# Generated by Django 5.2.17 on 2026-09-26 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_created_by_alter_payment_received_by'),
        ('patients', '0003_patient_hospital_alter_patient_patient_id_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Tenant - kaunsa hospital yeh record own karta hai', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hospital'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Tenant - kaunsa hospital yeh record own karta hai', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hospital'),
        ),
        migrations.AddField(
            model_name='payment',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Tenant - kaunsa hospital yeh record own karta hai', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hospital'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, editable=False, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('hospital', 'invoice_number'), name='uniq_invoice_number_per_hospital'),
        ),
    ]
