# Generated by Django 5.2.17 on 2026-09-26 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Kis hospital ka record touch hua - tenant-wise audit trail filter ke liye', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tenants.hospital'),
        ),
        migrations.AddField(
            model_name='idcounter',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Null = legacy/platform counter (multi-tenant se pehle ka)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_counters', to='tenants.hospital'),
        ),
        migrations.AlterField(
            model_name='idcounter',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['hospital', '-timestamp'], name='core_auditl_hospita_60127c_idx'),
        ),
        migrations.AddConstraint(
            model_name='idcounter',
            constraint=models.UniqueConstraint(fields=('name', 'hospital'), name='uniq_counter_per_hospital'),
        ),
    ]
