# Generated by Django 5.2.17 on 2026-09-26 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0005_appointment_hospital_not_null'),
        ('tenants', '0002_assign_default_hospital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoShowModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=60, unique=True)),
                ('algorithm', models.CharField(default='GradientBoostingClassifier', max_length=60)),
                ('relative_path', models.CharField(max_length=255)),
                ('training_rows', models.PositiveIntegerField(default=0)),
                ('positive_rate', models.FloatField(default=0, help_text='Training set mein no-show ka hissa')),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('feature_names', models.JSONField(blank=True, default=list)),
                ('feature_importances', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True, help_text='Prediction ke liye yahi version use ho')),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(blank=True, help_text='NULL = sab hospitals ka data mila ke train hua (global model)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_show_models', to='tenants.hospital')),
                ('trained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='0.0 - 1.0; jitna zyada, no-show ka chance utna zyada')),
                ('level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_index=True, default='LOW', max_length=10)),
                ('engine', models.CharField(choices=[('rules', 'Rule-based (cold start)'), ('sklearn', 'GradientBoosting')], default='rules', max_length=10)),
                ('reasons', models.JSONField(blank=True, default=list, help_text='Human-readable wajah: [{"factor": "lead_time", "impact": 0.12, "note": "..."}]')),
                ('model_version', models.CharField(blank=True, max_length=60)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk', to='appointments.appointment')),
                ('hospital', models.ForeignKey(help_text='Tenant - kaunsa hospital yeh record own karta hai', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hospital')),
            ],
            options={
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['level', '-score'], name='ml_engine_a_level_0b1ee0_idx')],
            },
        ),
    ]
