# Generated by Django 5.2.17 on 2026-09-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hospital ka display naam', max_length=150)),
                ('slug', models.SlugField(help_text="Subdomain - acme.example.com ke liye 'acme'. Lowercase, no spaces.", max_length=63, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='False = subscription lapse / suspend. Login block ho jaata hai, data safe rehta hai.')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
