# Generated by Django 5.2.17 on 2026-09-26 09:40

import django.contrib.auth.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Which hospital this login belongs to. NULL = platform super-admin.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='tenants.hospital'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_platform_admin',
            field=models.BooleanField(default=False, help_text='Platform (SaaS) operator - can see all hospitals. OFF for hospital staff.'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('hospital', 'username'), name='uniq_username_per_hospital'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('email__gt', '')), fields=('hospital', 'email'), name='uniq_email_per_hospital'),
        ),
    ]
