# Generated by Django 5.2.17 on 2026-09-26 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('wards', '0003_alter_admission_admitted_by_alter_admission_bed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Tenant - which hospital owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hospital'),
        ),
        migrations.AddField(
            model_name='bed',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Tenant - which hospital owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hospital'),
        ),
        migrations.AddField(
            model_name='ward',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Tenant - which hospital owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hospital'),
        ),
    ]
