# Generated by Django 5.2.17 on 2026-09-26 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_assign_default_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField(help_text='e.g. starter, growth', max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Per billing period, INR mein (Razorpay ko paisa mein bhejte hain)', max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('patient_limit', models.IntegerField(default=100, help_text='Isse zyada patients nahi. -1 = unlimited')),
                ('staff_limit', models.IntegerField(default=5, help_text='Kitne staff logins. -1 = unlimited')),
                ('appointment_limit', models.IntegerField(default=-1, help_text='Monthly appointments. -1 = unlimited')),
                ('features_json', models.JSONField(blank=True, default=dict, help_text='{"ai_no_show": true, "api_access": false, ...}. Jo key missing ho uski default False maani jaati hai.')),
                ('razorpay_plan_id', models.CharField(blank=True, help_text='Razorpay pe bana hua plan id (plan_xxx). Recurring checkout ke liye zaroori.', max_length=60)),
                ('trial_days', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='False = naye subscriptions band')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIALING', 'Trialing'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('HALTED', 'Halted')], default='PENDING', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('razorpay_subscription_id', models.CharField(blank=True, db_index=True, max_length=60)),
                ('razorpay_customer_id', models.CharField(blank=True, max_length=60)),
                ('razorpay_plan_id', models.CharField(blank=True, max_length=60)),
                ('last_payment_id', models.CharField(blank=True, max_length=60)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.OneToOneField(blank=True, help_text='NULL = platform-level / unassigned (tenant backfill ke liye)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.hospital')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=80, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'current_period_end'], name='subscriptio_status_3d1ac5_idx'),
        ),
    ]
